---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsgenerators/finalizers
  verbs:
  - update
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsgenerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsproviders/finalizers
  verbs:
  - update
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - dns.xzzpig.com
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
